version: "3"
services:
  namedtuple_sample:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: namedtuple_sample-image
    container_name: namedtuple_sample-container
    tty: true
